# Setup
title:        Build A Personal Power Plant
tagline:      Share how-tos & parts lists, discuss, and learn.
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
