# Setup
title:        Homebrewed Solar.
tagline:      A guide to building solar micro-grids in your bedroom with parts off Amazon. Sub-$300 solar self-sufficiency – without your landlord noticing. Today's total for the basic ingredients is $224.98
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://nikodunk.github.io/gridlesskits

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown