# Setup
title:        sunboxlabs
tagline:      is a platform for sharing DIY solar projects. learn, share, build.
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
