# Setup
title:        Personal Power Plant projects
tagline:      Share your DIY solar panel & battery experiments, discuss & learn. 
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
