# Setup
title:        Build A Personal Power Plant For $200.
tagline:      A compact solar generator to provide silent, fuel-free power for off-grid appliances at home, in power outages, outdoors or at festivals.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://gridlesskits.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
