# Setup
title:        Homebrewed Solar.
tagline:      Build solar micro-grids in your bedroom with parts off Amazon. For sub-$300 solar self-sufficiency – without your landlord noticing. Today's total for the basic ingredients is $224.98
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://gridlesskits.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown