# Setup
title:        sunboxlabs
tagline:      solar panel + battery backup power with part costs and prices from Amazon.
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
