# Setup
title:        DIY Solar + Storage&#58; Build A Personal Power Plant
tagline:      Share How-Tos & Parts Lists, discuss hacks, and learn&#58;
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
