# Setup
title:        Solar + battery knowledge for everyone.
tagline:      Share experiments, your DIY solar builds, research, discuss & learn. 
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
