# Setup
title:        Solar & Batteries for everyone.
tagline:      Share your DIY solar experiments, discuss & learn. 
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
