# Setup
title:        Homebrew Solar.
tagline:      We help hackers build personal power plants with parts off Amazon. DIY solar self-sufficiency on a shoestring. <br> The Basic Homebrew Kit currently costs $224.98&#58;
baseurl:      ""
paginate:     3

# About/contact
author:
  name:       Author name
  url:        http://gridlesskits.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
