# Setup
title:        Solar + Batteries for everyone.
tagline:      Share knowledge, your DIY solar experiments, research, build, discuss & learn. 
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
