# Setup
title:        Build A Personal Power Plant For $200.
tagline:      A compact solar generator to provide silent, fuel-free power for festivals, power outages, camping or off-grid applications at home.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Niko Dunk
  url:        http://gridlesskits.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
