# Setup
title:        The Personal Power Plant Is Here.
tagline:      Fuelbox is a compact solar generator that silently provides off-grid power at home, festivals or outdoors. <br>Build the system yourself or order one pre-assembled&#58;
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://gridlesskits.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
