# Setup
title:        Build A Personal Power Plant For $200.
tagline:      A compact solar generator you can build yourself – for silent, fuel-free power
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Niko Dunk
  url:        http://gridlesskits.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
