# Setup
title:        Build A Personal Power Plant. It's time.
tagline:      How to build a compact solar generator with parts from Amazon – for silent, fuel-free power
baseurl:      ""
paginate:     2

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
