# Setup
title:        Homebrew Solar.
tagline:      We help hackers build micro-grids in their bedrooms with parts off Amazon. Solar self-sufficiency – without your landlord noticing. Today the basic components cost is $224.98
baseurl:      ""
paginate:     3

# About/contact
author:
  name:       Author name
  url:        http://gridlesskits.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown