# Setup
title:        Build A Personal Power Plant.
tagline:      How to build a compact solar generator with parts from Amazon – for silent, fuel-free power
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Niko Dunk
  url:        http://projectsunbox.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
