# Setup
title:        Personal Powerplants are Possible
tagline:      Post DIY solar projects | ask questions | submit links | request projects
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
