# Setup
title:        sunboxlabs
tagline:      solar panel prices + battery backup power costs on Amazon.
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
