# Setup
title:        sunboxlabs
tagline:      DIY Solar with parts off Amazon.
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Niko Dunk
  url:        http://sunboxlabs.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
