# Setup
title:        Build A Personal Power Plant For $200.
tagline:      A compact solar generator that silently provides off-grid power at home, outdoors or at festivals.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://gridlesskits.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
