# Setup
title:        Homebrewed Solar.
tagline:      Build a micro-grid in your bedroom with parts off Amazon.<br>Solar self-sufficiency – without your landlord noticing. Today the basic kit is $224.98
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://gridlesskits.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown